// integrations/vue2/src/components/EmailEditor.vue
<template>
  <div>
    <div class="iframeWrapper">
      <iframe
        ref="iframeRef"
        width="100%"
        height="100%"
        :src="url"
        @load="onIframeLoad"
      ></iframe>
    </div>
    <button @click="getJsonTemplate">JSON</button>
    <button @click="getHtmlTemplate">HTML</button>
    <button @click="toggleSamples">toggle samples</button>
    <button @click="toggleInspector">toggle inspector</button>
    <button @click="loadTemplate(json)">load template</button>
    <textarea v-model="json"></textarea>
    <textarea v-model="html" readonly></textarea>
  </div>
</template>

<script>
export default {
  name: 'EmailEditor',
  props: {
    url: String
  },
  data() {
    return {
      json: "",
      html: "",
    };
  },
  methods: {
    getJsonTemplate() {
      return this.$refs.iframeRef.sendMessage({ method: 'getJson' }).then(response => {
        console.log("Response from child:", response);
        return response;
      }).catch(err => console.error(err));
    },
    getHtmlTemplate() {
      return this.$refs.iframeRef.sendMessage({ method: 'getHtml' }).then(response => {
        console.log("Response from child:", response);
        return response;
      }).catch(err => console.error(err));
    },
    toggleSamples() {
      return this.$refs.iframeRef.sendMessage({ method: 'toggleSamplesDrawerOpen' }).then(response => {
        console.log("Response from child:", response);
        return response;
      }).catch(err => console.error(err));
    },
    toggleInspector() {
      return this.$refs.iframeRef.sendMessage({ method: 'toggleInspectorDrawerOpen' }).then(response => {
        console.log("Response from child:", response);
        return response;
      }).catch(err => console.error(err));
    },
    loadTemplate(jsonText) {
      return this.$refs.iframeRef.sendMessage({
        method: 'resetDocument',
        args: [jsonText]
      }).then(response => {
        console.log("Response from child:", response);
        return response
      }).catch(err => console.error(err));
    },
    onIframeLoad() {
    }
  },
  mounted() {
    const iframe = this.$refs.iframeRef;
    if (window.integrator) {
      window.integrator.addIframe(iframe);
      iframe.addEventListener('watch.json', e => {
        this.json = e.detail;
      });
      iframe.addEventListener('watch.html', e => {
        this.html = e.detail;
      });
    }
  },
};
</script>

<style scoped>
.iframeWrapper {
  display: flex;
  width: 100%;
  height: 100vh;
  overflow: hidden;
}
</style>

// integrations/angular/src/app/email-editor/email-editor.component.ts
import { Component, ViewChild, ElementRef, AfterViewInit, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';

@Component({
  selector: 'app-email-editor',
  templateUrl: './email-editor.component.html',
  styleUrls: ['./email-editor.component.css'],
  imports: [FormsModule]
})
export class EmailEditorComponent implements AfterViewInit {
  @Input() set url(value: string) {
    this.iframeUrl = this.sanitizer.bypassSecurityTrustResourceUrl(value);
  }
  iframeUrl!: SafeResourceUrl;
  json: string = '';
  html: string = '';

  @ViewChild('iframeRef') iframeRef!: ElementRef;

  constructor(private sanitizer: DomSanitizer) {}

  ngAfterViewInit() {
    const iframe = this.iframeRef.nativeElement;
    console.log(iframe);
    if (window.integrator) {
      window.integrator.addIframe(iframe);
      iframe.addEventListener('watch.json', (e:any) => {
        this.json = e.detail;
      });
      iframe.addEventListener('watch.html', (e:any) => {
        this.html = e.detail;
      });
    }
  }

  onIframeLoad() {
    console.log('editor loaded');
  }

  getJsonTemplate() {
    return this.iframeRef.nativeElement.sendMessage({ method: 'getJson' }).then((response: any) => {
      console.log("Response from child:", response);
      return response;
    }).catch((err: any) => console.error(err));
  }
  getHtmlTemplate() {
    return this.iframeRef.nativeElement.sendMessage({ method: 'getHtml' }).then((response: any) => {
      console.log("Response from child:", response);
      return response;
    }).catch((err: any) => console.error(err));
  }
  toggleSamples() {
    return this.iframeRef.nativeElement.sendMessage({ method: 'toggleSamplesDrawerOpen' }).then((response: any) => {
      console.log("Response from child:", response);
      return response;
    }).catch((err: any) => console.error(err));
  }
  toggleInspector() {
    return this.iframeRef.nativeElement.sendMessage({ method: 'toggleInspectorDrawerOpen' }).then((response: any) => {
      console.log("Response from child:", response);
      return response;
    }).catch((err: any) => console.error(err));
  }
  loadTemplate(jsonText: String) {
    return this.iframeRef.nativeElement.sendMessage({
      method: 'resetDocument',
      args: [jsonText]
    }).then((response: any) => {
      console.log("Response from child:", response);
      return response
    }).catch((err: any) => console.error(err));
  }
}
<div class="iframeWrapper">
    <iframe #iframeRef width="100%" height="100%" [src]="iframeUrl" (load)="onIframeLoad()"></iframe>
</div>
<button (click)="getJsonTemplate()">JSON</button>
<button (click)="getHtmlTemplate()">HTML</button>
<button (click)="toggleSamples()">toggle samples</button>
<button (click)="toggleInspector()">toggle inspector</button>
<button (click)="loadTemplate(json)">load template</button>
<textarea [(ngModel)]="json"></textarea>
<textarea [(ngModel)]="html" readonly></textarea>
