// integrations/angular/src/app/email-editor/email-editor.component.ts
import { Component, ViewChild, ElementRef, AfterViewInit, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';

@Component({
  selector: 'app-email-editor',
  templateUrl: './email-editor.component.html',
  styleUrls: ['./email-editor.component.css'],
  imports: [FormsModule]
})
export class EmailEditorComponent implements AfterViewInit {
  @Input() set url(value: string) {
    this.iframeUrl = this.sanitizer.bypassSecurityTrustResourceUrl(value);
  }
  iframeUrl!: SafeResourceUrl;
  json: string = '';
  html: string = '';

  @ViewChild('iframeRef') iframeRef!: ElementRef;

  constructor(private sanitizer: DomSanitizer) {}

  ngAfterViewInit() {
    const iframe = this.iframeRef.nativeElement;
    console.log(iframe);
    if (window.integrator) {
      window.integrator.addIframe(iframe);
      iframe.addEventListener('watch.json', (e:any) => {
        this.json = e.detail;
      });
      iframe.addEventListener('watch.html', (e:any) => {
        this.html = e.detail;
      });
    }
  }

  onIframeLoad() {
    console.log('editor loaded');
  }

  getJsonTemplate() {
    return this.iframeRef.nativeElement.sendMessage({ method: 'getJson' }).then((response: any) => {
      console.log("Response from child:", response);
      return response;
    }).catch((err: any) => console.error(err));
  }
  getHtmlTemplate() {
    return this.iframeRef.nativeElement.sendMessage({ method: 'getHtml' }).then((response: any) => {
      console.log("Response from child:", response);
      return response;
    }).catch((err: any) => console.error(err));
  }
  toggleSamples() {
    return this.iframeRef.nativeElement.sendMessage({ method: 'toggleSamplesDrawerOpen' }).then((response: any) => {
      console.log("Response from child:", response);
      return response;
    }).catch((err: any) => console.error(err));
  }
  toggleInspector() {
    return this.iframeRef.nativeElement.sendMessage({ method: 'toggleInspectorDrawerOpen' }).then((response: any) => {
      console.log("Response from child:", response);
      return response;
    }).catch((err: any) => console.error(err));
  }
  loadTemplate(jsonText: String) {
    return this.iframeRef.nativeElement.sendMessage({
      method: 'resetDocument',
      args: [jsonText]
    }).then((response: any) => {
      console.log("Response from child:", response);
      return response
    }).catch((err: any) => console.error(err));
  }
}
<div class="iframeWrapper">
    <iframe #iframeRef width="100%" height="100%" [src]="iframeUrl" (load)="onIframeLoad()"></iframe>
</div>
<button (click)="getJsonTemplate()">JSON</button>
<button (click)="getHtmlTemplate()">HTML</button>
<button (click)="toggleSamples()">toggle samples</button>
<button (click)="toggleInspector()">toggle inspector</button>
<button (click)="loadTemplate(json)">load template</button>
<textarea [(ngModel)]="json"></textarea>
<textarea [(ngModel)]="html" readonly></textarea>

// integrations/vue/src/components/EmailEditor.vue
<script setup>
import { ref, onMounted, onBeforeMount } from "vue";

const props = defineProps({
  url: {
    type: String,
    required: true,
  },
});

const iframeRef = ref(null);
const iframeUrl = ref(props.url);
const json = ref('');
const html = ref('');

const onIframeLoad = () => {
  console.log("Iframe loaded:", iframeUrl.value);
};

const loadTemplate = (jsonText) => {
  return iframeRef.value.sendMessage({
    method: 'resetDocument',
    args: [jsonText]
  }).then(response => {
    console.log("Response from child:", response);
    html.value = response;
    return response
  }).catch(err => console.error(err));
};

const getJsonFromIframe = () => {
  return iframeRef.value.sendMessage({ method: 'getJson' }).then(response => {
    console.log("Response from child:", response);
    return response;
  }).catch(err => console.error(err));
};

const getHtmlFromIframe = () => {
  return iframeRef.value.sendMessage({ method: 'getHtml' }).then(response => {
    console.log("Response from child:", response);
    return response;
  }).catch(err => console.error(err));
};

const toggleSamples = () => {
  return iframeRef.value.sendMessage({ method: 'toggleSamplesDrawerOpen' }).then(response => {
    console.log("Response from child:", response);
    return response;
  }).catch(err => console.error(err));
};

const toggleInspector = () => {
  return iframeRef.value.sendMessage({ method: 'toggleInspectorDrawerOpen' }).then(response => {
    console.log("Response from child:", response);
    return response;
  }).catch(err => console.error(err));
};

const getJsonTemplate = () => {
  getJsonFromIframe().then(e => {
    console.log(e);
    json.value = e;
  });
};

const getHtmlTemplate = () => {
  getHtmlFromIframe().then(e => {
    console.log(e);
    html.value = e;
  });
};

onBeforeMount(() => {
  console.log("Component is about to be mounted");
});

onMounted(() => {
  const iframe = iframeRef.value;
  if (window.integrator) {
    window.integrator.addIframe(iframe);
    iframe.addEventListener('watch.json', e => {
      json.value = e.detail;
    });
    iframe.addEventListener('watch.html', e => {
      html.value = e.detail;
    });
  }
});
</script>

<template>
  <div class="iframeWrapper">
    <iframe
      ref="iframeRef"
      width="100%"
      height="100%"
      :src="iframeUrl"
      @load="onIframeLoad"
    ></iframe>
  </div>
  <button @click="getJsonTemplate">JSON</button>
  <button @click="getHtmlTemplate">HTML</button>
  <button @click="toggleSamples">toggle samples</button>
  <button @click="toggleInspector">toggle inspector</button>
  <button @click="loadTemplate(json)">load template</button>
  <textarea v-model="json"></textarea>
  <textarea v-model="html" readonly></textarea>
</template>

<style scoped>
.iframeWrapper {
  display: flex;
  width: 100%;
  height: 100vh;
  overflow: hidden;
}
</style>
